### ISSUE TITLE
[Bug] Soulbinding enchant not working

### ISSUE THREAD

**Issue by Luke616** [TheIllusiveC4/CorpseComplex#8]
Title, happening in version 1.0.1.1 for MC 1.12.2. Was able to reproduce in both SSP and SMP. Soulbound-enchanted objects were still dropping on death. Here are the configs for my inventory and soulbound modules:

```
##########################################################################################################
# inventory
#--------------------------------------------------------------------------------------------------------#
# Customize how your inventory is handled on death and respawn
##########################################################################################################

inventory {
    # Set to true to enable inventory module
    B:"Enable Inventory Module"=true

    # Set to true to keep equipped armor on death
    B:"Keep Armor"=true

    # Set to true to keep non-mainhand hotbar items on death
    B:"Keep Hotbar"=true

    # Set to true to keep mainhand item on death
    B:"Keep Mainhand"=true

    # Set to true to keep offhand item on death
    B:"Keep Offhand"=true

    # Set to true to keep main inventory (non-equipped non-hotbar) items on death
    B:"Keep Main Inventory"=true

    # Percent of durability lost on death for drops
    D:"Durability Loss on Drops"=0.0

    # Percent of durability lost on death for kept items
    D:"Durability Loss on Kept Items"=0.0

    # Percent of energy drained on death for drops
    D:"Energy Drain on Drops"=0.0

    # Percent of energy drained on death for kept items
    D:"Energy Drain on Kept Items"=0.0

    # Percent chance that items that are kept will still drop
    D:"Random Drop Chance"=0.5

    # Percent chance that dropped items will be destroyed
    D:"Random Destroy Chance"=0.0

    # List of items that are always kept
    S:"Essential Items" <
        antiqueatlas:antique_atlas
        theoneprobe:probe
        theoneprobe:probe_goggles
        questbook:itemquestbook
        minecraft:compass
		everlastingabilities:ability_bottle
     >

    # List of items that are always dropped
    S:"Cursed Items" <
     >

    # Set to true to destroy cursed items instead of dropping them
    B:"Destroy Cursed Items"=false

    # Set to true to keep Baubles on death
    B:"Keep Baubles"=true

    ##########################################################################################################
    # soulbinding
    #--------------------------------------------------------------------------------------------------------#
    # Enable and customize the soulbinding enchantment
    ##########################################################################################################

    soulbinding {
        # Set to true to enable Soulbinding enchantment
        B:"Enable Soulbinding Enchantment"=true

        # The max level of the enchantment
        I:"Max Level"=1

        # The percent chance that the item will drop a level in the enchantment on death when kept
        D:"Chance to Drop Level on Saved Item"=0.0

        # The base percent chance that the enchantment will save an item on death regardless of level
        D:"Base Save Probability"=1.0

        # The percent chance increase that each level in the enchantment will give to saving an item on death
        D:"Extra Save Probability per Level"=0.0

        # Set to true to allow enchanting Soulbinding at the enchantment table
        B:"Can Apply at Enchanting Table"=true

        # Set to true to allow enchanting Soulbinding on books
        B:"Allowed on Books"=true

        # The rarity of the enchantment (COMMON, UNCOMMON, RARE, or VERY_RARE)
        S:Rarity=VERY_RARE
    }

}
```

Thanks!
Luke616

**Comment by TheIllusiveC4** [comment]
I have successfully replicated this bug. This definitely worked back in version 1.0.0, so something must have broken between updates. I'm working on a fix right now.

**Comment by TheIllusiveC4** [comment]
After looking into it, this definitely didn't work back in version 1.0.0 either. My mistake. Regardless, I've fixed this issue internally and it will be included in the next update.

**Comment by TheIllusiveC4** [comment]
I've pushed out a new update, version 1.0.1.2, that should fix this issue. Please let me know if the problem continues so I can reopen this. Thank you very much for your submission.

**Comment by Luke616** [comment]
Can confirm that the XP bug is still occurring. It seems like it'll happen randomly, but then after that one first death the XP drops regularly.

Here is a modlist of the environment in which this is occurring. Do you think some other mod may be contributing to cause the bug?
https://pastebin.com/W1G8Nikv

**Comment by TheIllusiveC4** [comment]
I'll assume you meant to post this in the other issue [here](https://github.com/TheIllusiveC4/CorpseComplex/issues/7) and post my relevant comment in that thread.
